### ISSUE TITLE
Ansible Host Key Checking

### ISSUE THREAD

**Issue by CrazySwe** [GroupOneIncorporated/acme-infrastructure#17]
Ansible does host key checking and it will give error if there is a new machine by wrong key in ~/.ssh/known_hosts 
Could be solved by turning off the key checking as mentioned here:
[https://docs.ansible.com/ansible/latest/user_guide/connection_details.html#managing-host-key-checking](https://docs.ansible.com/ansible/latest/user_guide/connection_details.html#managing-host-key-checking)

**Comment by CrazySwe** [comment]
Temporary fix in 9a2f8c261fbbf164de67ca0a5b0e2aac60c558a9

**Comment by brocahontaz** [comment]
Closing as the fix in 9a2f8c2 works fine for now.

Free to reopen if wanted.
