### ISSUE TITLE
Automate ssh config

### ISSUE THREAD

**Issue by brocahontaz** [GroupOneIncorporated/acme-infrastructure#8]
Add automated include of ssh config file to local ssh config.

**Comment by CrazySwe** [comment]
Added to write over the current config with a7f6973a6a18b4d0e1951662d6e5217ea986960a
Should maybe be done with appending or concatenating files instead?

**Comment by brocahontaz** [comment]
Needs to be done by concatenation instead, as I have other stuff in my ssh config that I can't lose.
